### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by KraXen72** [diogenesofweb/focus#1]
hi, great app! i have a few feature requests, please consider them individually and implement ones you think would be useful & have motivation to do:
- show the current timer progres in `<title>` so i can see state even when not on the tab. it's ok if updates every second or every 5
- super simple stopwatch mode
- a setting where the break & next mode auto-starts without user input - would be useful
- more freedom - ability to not just schedule long or short break, but to give a name + custom length for each break & activity,
    - possibly custom icon + color? so ican schedule tasks in order with names & icons
- popup / PictureInPicture / chrome extension mode? so i can easily put it on second monitor or something
- change ukraine emoji in footer from emoji to svg, as on windows it only renders as the letters UA
  
 there are also a few bugs:
- the app flashes a bit of white theme before it loads the preferences - maybe avoid rendering unless it's restored?
- the github is not linked from the main site, maybe put it in the footer?

i know svelte myself and if there are some that you think would be nice but don't have the time/motivation to implement, let me know and i can probably pr them. i' d just figured i ask first before i start yet another of the infinite sideprojects i have.........

**Comment by diogenesofweb** [comment]
Hi! Thank you for your feedback! 

I’ve fixed the flash with a dark theme, added a timer to <title /> and two autostarts options.

> more freedom - ability to not just schedule long or short break, but to give a name + custom length for each break & activity

I’ve started to play with the idea, but I can't figure out how labels & icons for tasks should look like.

> super simple stopwatch mode

Is it like showing the time passed since the end of a focus period?

> popup / PictureInPicture / chrome extension mode?

I often use Firefox and extensions aren't my thing.  That said, some kind of floating window would be nice to add, but I have no idea how to do it. What are the options besides extensions?

**Comment by KraXen72** [comment]
thanks!
- for more freedom, you could just include the material icons icon font in one particular configured style you like
    - thick/thin, rouned/sharp etc wouldn't be configurable, youd configure that once in material fonts webpage and download the woff2 file they link to in the stylesheet to selfhost it, i've done it in the past, for example [here](https://github.com/KraXen72/fabric-moodboard/blob/master/src/css/material-icons.css)
- super simple stopwatch mode is something like [niagara](https://niagara.vercel.app) i could use that but having them both on one page would be nice.
- popup window: [stackoverflow post for svelte popup window](https://stackoverflow.com/questions/58187495/create-window-with-attached-svelte-component-and-in-the-same-javascript-context), the [repl](https://svelte.dev/repl/6762fb104bfd411caa9c792865f53d67?version=3.12.1) there are also probably other ways to do this too this is just one way

**Comment by diogenesofweb** [comment]
Added possibility to set icons & labels & time for each focus & break periods. 

The next in the list are stopwatch and popup window. 
Are you interested in implementing one or both of them?

**Comment by KraXen72** [comment]
currently, i don't have too much free time, but once i do have some time i could add the stopwatch probably.

**Comment by KraXen72** [comment]
i just saw the site again, and i have to say, very nice design refresh!
also, for your information, you can name your git commits different things than just 'Up (date)'. for example, you can take a look at how [this developer](https://github.com/OxygenCobalt/Auxio/commits/dev) names their commits. Just a suggestion though, if this works for you, than that's good too. I still have the stopwatch for this site in my project backlog, possibly i'll get to it during the next few weeks.

**Comment by diogenesofweb** [comment]
Oh, I wish I could name like that, but currently I use commits just as a way to trigger site deploy.

**Comment by diogenesofweb** [comment]
Stopwatch added, usable in a separate page or as an addon.

**Comment by KraXen72** [comment]
very nice!!!! resetting the stopwatch while running does pause it, but the button still looks like it's running.

**Comment by diogenesofweb** [comment]
FIxed, thanks for reporting!

**Comment by KraXen72** [comment]
Hi, where are you supposed to setup/change sequences in the new update? I couldn't find it anywhere, only switch the existing ones. thanks!

**Comment by KraXen72** [comment]
ah okay, i found it.

**Comment by KraXen72** [comment]
hello! it would be great if we could skip to a certain session in our pomodoro by clicking on these icons:
![image](https://github.com/diogenesofweb/focus/assets/21956756/279c7dba-651d-40f6-bfd2-8c90611f67ad)

currently, i can only skip forwards with next, but i can't go back without resetting. i often accidentally hit next instead of resume or whatever's the proper option, so i would be glad if i can go back to where i was. Thanks!

**Comment by diogenesofweb** [comment]
Added select active phase on icon click

**Comment by KraXen72** [comment]
hi! 
i found some new bugs:
- when clicking on the active phase, it's always the first name for the session that gets used.
for example, if i have 4 60min sessions named "hour 1", "hour 2", etc. clicking on any of the work sessions will display "hour 1"
- radio venice classic and freecodecamp radio dont' work for me - maybe their url updated?

also, thanks for making this awesome pomodoro timer! i'm sure i've probably said it in the past, but i use it a lot and it's awesome!

**Comment by KraXen72** [comment]
i have another feature request i have: when you hold shift, the volume input for radio step is 1 instead of 5 for more precision. not high priority, since i can easily inspect element and change the step, but would be nice to have.

**Comment by diogenesofweb** [comment]
Hi!
Glad to hear you are using the tool, meaning I'm not alone. 

Hopefully fixed the issue with selecting the active phase. Set volume step to 1. 
About radios. /radio-stations have a button ‘reset to default’. You may try it, FCC radio will work, but the action will erase all previously added stations.

**Comment by KraXen72** [comment]
Hello! can you please either change the alarm input box to be 24 hours, or atleast add it as a setting?
I use 24h time and trying to do am/pm conversions, esp around noon/midnight is always confusing and i have to look it up lol.
I am talking about this:

![Image](https://github.com/user-attachments/assets/3e392975-a7f7-4f2e-ad95-c4c62f649752)

thank you!

**Comment by diogenesofweb** [comment]
It's just ```<input type="time">```

Browser decides what hour cycle, 12h or 24h, to use based on the device localization settings.  

You may need to change your language preferences.

I've set 'English (GB)' on firefox and it shows 24h cycle, no AM/PM
